source 'https://github.com/dji-sdk/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # DJI Mobile SDK V4 for iOS
  pod 'DJI-SDK-iOS', '~> 4.16.1'

  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'

      # Suppress warnings from DJI SDK
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
    end
  end
end
